---
- name: install logrotate
  yum:
    name: logrotate
    state: present
- name: get docker-gen to generate logrotate & awslogs.conf
  get_url:
    url: https://github.com/jwilder/docker-gen/releases/download/0.3.9/docker-gen-linux-amd64-0.3.9.tar.gz
    dest: /tmp/docker-gen-linux-amd64-0.3.3.tar.gz
- name: unpack docker-gen to /bin
  unarchive:
    src: /tmp/docker-gen-linux-amd64-0.3.3.tar.gz
    dest: /bin/
- name: get couchdb docker image
  shell: docker pull mredar/couchdb
- name: run couchdb docker
  docker:
    state: running
    image: tutum/couchdb
    name: couchdb
    ports: 5984:5984
    env: COUCHDB_PASS={{ COUCHDB_PSWD }}
    volumes: /var/lib/couchdb:/var/lib/couchdb
- name: copy logrotate docker-gen template to /tmp
  copy:
    src: logrotate-docker-gen.tmpl
    dest: /tmp/logrotate-docker-gen.tmpl
- name: create logrotate for couchdb container
  shell: /bin/docker-gen /tmp/logrotate-docker-gen.tmpl /etc/logrotate.d/docker
- name: copy awslogs docker-gen template to /tmp
  copy:
    src: awslogs-docker-gen.tmpl
    dest: /tmp/awslogs-docker-gen.tmpl
- name: create awslogs.conf for couchdb docker container
  shell: /bin/docker-gen /tmp/awslogs-docker-gen.tmpl /etc/awslogs/awslogs.conf
#TODO: need to get the password or create it....
#TODO: for harvester user
#TODO: run dpla scripts/sync_db
