---
# this can't be the right way to do this
- name: figure out the current user
  shell: whoami
  register: whoami
- name: figure out the home directory
  shell: "getent passwd $(whoami) | cut -d: -f6"
  register: role_home_dir
- name: figure out the hostname
  shell: ~/appstrap/ansible/myhostname
  register: hostname
