---
# tasks file for majorTom
- debug: name=role_home_dir
- name: uninstall centos docker io
  yum:
    pkg: docker-io
    state: absent
  when: ansible_distribution == "CentOS"
- name: install amazon linux docker io
  yum:
    pkg: docker
    state: absent
  when: ansible_distribution == "Amazon"
- name: put bashrc with auto activation of workers_local virturalenv
  template:
    src: bashrc.j2
    dest: ~/.bashrc
    mode: 0600
    backup: yes
    force: yes
  tags: bashrc
- name: get ec2 inventory script
  get_url:
    url: https://raw.githubusercontent.com/ansible/ansible/devel/plugins/inventory/ec2.py
    dest: "{{ role_home_dir.stdout }}/code/ec2.py"
    mode: 0755
- name: copy ec2 inventory ini
  copy:
    src: ec2.ini
    dest: "{{ role_home_dir.stdout }}/code/ec2.ini"
    mode: 0644
- name: read in ingest private key from vaulted file
  include_vars: ingest-private.pem.yml
- name: put ingest-private.pem in place
  template:
    src: ingest-private.pem.j2
    dest: "{{ role_home_dir.stdout }}/.ssh/ingest-private.pem"
    mode: 0600
- name: set .ssh dir
  file:
    state: directory
    mode: 0700
    dest: "{{ role_home_dir.stdout }}/.ssh"
- name: put ssh config in place to make ingest-private default identity
  template:
    src: ssh_config
    dest: "{{ role_home_dir.stdout }}/.ssh/config"
    mode: 0600
    owner: ec2-user
