---
# tasks file for create_worker_instance
- name: create a new worker instance in the private vpc
  local_action:
    module: ec2
    count: 1
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: ingest-control
    group_id: [ "{{ sec_grp_ingest_private_id }}" ]
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_private }}"
    assign_public_ip: yes
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env}}-worker"
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: 8
      delete_on_termination: yes
  register: ec2_worker
- debug: var=ec2_worker
