---
# there should be registered variable ec2_info that is the result of a
# call to the ec2 module creating instances
- name: get associated volume for created instance
  ec2_vol:
    region: "{{ region }}"
    instance: "{{ item }}"
    state: list
  register: volumes_out
  with_items: "{{ ec2_info.instance_ids }}"
- name: tag associated volume
  ec2_tag:
    resource: "{{ item.id }}"
    region: "{{ region }}"
    tags:
        project: "{{ project }}"
        Name: "{{ name_env}}-worker"
        Program: dsc
        Environment: prd
        Service: calisphere
  with_items: "{{ volumes_out.volumes | default([]) }}"

