---
- name: create the couchdb ingest instance
  local_action:
    module: ec2
    count: 1
    state: present #safe?
    region: "{{ region }}"
    key_name: "{{ key_name_private }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ instance_type }}"
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_private }}"
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env }}-couchdb"
    volumes:
    - device_name: /dev/sdb
      device_type: gp2
      volume_size: "{{ extra_volume_size }}"
      delete_on_termination: "{{ dev_env }}"
      virtual_name: /var
  register: ec2_ingest_couchdb
- { include: protect_instance_from_termination.yml, instance_id: "{{ ec2_ingest_couchdb.instance_ids[0] }}", root_device_name: "{{ ec2_ingest_couchdb.instances[0].root_device_name }}", when: not dev_env }
