---
# tasks file for create_instances
- name: create the front end instance
  ec2:
    count: 1
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: ingest-front
    group_id: [ "{{ sec_grp_ingest_private.group_id }}",  "{{ sec_grp_front.group_id }}" ]
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_public }}"
    assign_public_ip: yes
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env}}-front"
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: 16
      delete_on_termination: "{{ prod_env == False }}"
  register: ec2_ingest_front
- debug: var=ec2_ingest_front
- pause: minutes=5 #let instance come up
- { include: protect_instance_from_termination.yml, instance_id: "{{ ec2_ingest_front.instance_ids[0] }}", root_device_name: "{{ ec2_ingest_front.instances[0].root_device_name }}", when: prod_env }
- name: assign permanent elastic ip to front end
  ec2_eip:
    state: present
    instance_id: "{{ ec2_ingest_front.instance_ids[0] }}"
    region: "{{ region }}"
    state: present
    in_vpc: yes
    public_ip: "{{ eip_ingest_front }}"
  when: prod_env
