---
- name: create the couchdb ingest instance
  ec2:
    count: 1
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name_private }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: ingest-couchdb
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_private }}"
    group_id: [ "{{ sec_grp_ingest_private.group_id }}"]
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env }}-couchdb"
        Program: "{{ tag_cdl_program }}"
        Environment: "{{ tag_cdl_env }}"
        Service: "{{ tag_cdl_service }}"
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: 8
      delete_on_termination: "{{ prod_env == False}}"
    - device_name: /dev/xvdb
      device_type: gp2
      volume_size: "{{ volume_size_couchdb }}"
      delete_on_termination: "{{ prod_env == False}}"
      virtual_name: /var
  register: ec2_ingest_couchdb
- { include: protect_instance_from_termination.yml, instance_id: "{{ ec2_ingest_couchdb.instance_ids[0] }}", root_device_name: "{{ ec2_ingest_couchdb.instances[0].root_device_name }}", when: prod_env }
