---
# tasks file for create_instances
- name: create the majorTom for the ingest. Creates workers & hosts docker repo.
  ec2:
    count: 1
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ image_hvm }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: ingest-control
    group_id: [ "{{ sec_grp_ingest_private.group_id }}" ]
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_private }}"
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env}}-majorTom"
        Program: "{{ tag_cdl_program }}"
        Environment: "{{ tag_cdl_env }}"
        Service: "{{ tag_cdl_service }}"
    volumes:
    - device_name: /dev/xvda
      device_type: gp2
      volume_size: 16
      delete_on_termination: "{{ prod_env == False }}"
  register: ec2_ingest_majorTom
- debug: var=ec2_ingest_majorTom
- pause: minutes=5 #let instance come up
- { include: protect_instance_from_termination.yml, instance_id: "{{ ec2_ingest_majorTom.instance_ids[0] }}", root_device_name: "{{ ec2_ingest_majorTom.instances[0].root_device_name }}", when: prod_env }
