---
- name: Create rules from template #https://groups.google.com/forum/#!topic/ansible-project/a8y1v2-R8Zw
  template:
    src: front_end_rules.j2
    dest: roles/create_vpc/vars/rules.yml
- name: Load rules var
  include_vars: rules.yml
- name: create front end security group
  ec2_group:
    region: "{{ region }}"
    description: "Access to ssh and https proxy server"
    name: "{{ name_env }}-front"
    state: present
    vpc_id: "{{ vpc.vpc_id }}"
    rules: "{{ front_end_security_rules }}"
  register: sec_grp_front
- debug: var=sec_grp_front
- ec2_tag: resource={{ sec_grp_front.group_id }} state=present region={{ region }}
  args:
    tags:
      project: "{{ tag_project }}"
      subproject: "{{ tag_subproject }}"
      Name: "{{ name_env }}-front"
