---
# tasks file for create_instances
- name: create the front end instance
  local_action:
    module: ec2
    count: 1
    state: present
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    image: "{{ image_nat }}"
    instance_type: m3.medium
    instance_profile_name: ingest-control
    group_id: [ "{{ sec_grp_default_id | regex_replace('\"','')}}",  "{{ sec_grp_front_id }}" ]
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ subnet_id_public }}"
    assign_public_ip: yes
    instance_tags:
        project: "{{ tag_project }}"
        subproject: "{{ tag_subproject }}"
        Name: "{{ name_env}}-front"
    volumes:
    - device_name: /dev/sda1
      device_type: gp2
      volume_size: 16
      delete_on_termination: "{{ prod_env == False }}"
      virtual_name: /
  register: ec2_front
- debug: var=ec2_front
- pause: minutes=5 #let instance come up
- { include: protect_instance_from_termination.yml, instance_id: "{{ ec2_front.instance_ids[0] }}", root_device_name: "{{ ec2_front.instances[0].root_device_name }}", when: prod_env }
