---
- debug: msg="VPC basename--> {{ name_env }}"

- { include: create_vpc.yml }
- { include: create_front_end_security_grp.yml }
- name: save info needed for creating instances
  template:
    src: save_vpc_information_for_instances.j2
    dest: ./roles/create_infrastructure_instances/vars/main.yml
- name: save network information
  template: src=save_vpc_create_vars.j2 dest=./vpc-vars.yml
