# Create the infrastructure for the ingest process
# VPC, subnets, security groups, gateway, routing tables,
# nat instance(can it be the front end?),
#
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
      tag_project: "{{ project | default('ucldc') }}"
      tag_subproject: "{{ subproject | default('ingest') }}"
      project_name: "{{ tag_project }}-{{ tag_subproject }}"
      name_suffix: "{{ name_end | default('new') }}"
      name_env: "{{ project_name }}-{{ name_suffix }}"
      dev_env: "{{ dev | default(True) }}"
  tasks:
    - debug: var=dev_env
  roles:
    - { role: create_vpc, tags:["vpc"]}
