# Create the infrastructure for the ingest process
# VPC, subnets, security groups, gateway, routing tables,
# nat instance(can it be the front end?),
#
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
      tag_project: "{{ project | default('ucldc') }}"
      tag_subproject: "{{ subproject | default('ingest') }}"
      project_name: "{{ tag_project }}-{{ tag_subproject }}"
      name_suffix: "{{ name_end | default('new') }}"
      #name_env: "{{ project_name }}-{{ name_suffix }}"
      name_env: "{{ tag_project }}-{{ name_suffix }}"
      prod_env: "{{ production | bool | default(False) }}"
  tasks:
    - debug: var=prod_env
    - shell: echo "dev_env tests true"
      when: prod_env

#  roles:
#    - create_infrastructure_instances
