---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    role: majorTom
    dir_role_templates: "roles/{{ role }}/templates"
  roles:
    - { role: common, sudo: no, tags: common}
    - { role: worker, sudo: no, tags: worker}
    - { role: majorTom, sudo: no, tags: [ majorTom, bashrc ]}
