# Create new worker instance for ingest
# This will launch into the private VPC and use the private addresses
# for redis, couchdb and solr
#
---
#- hosts: localhost
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
      tag_project: "{{ project | default('ucldc') }}"
      tag_subproject: "{{ subproject | default('ingest') }}"
      project_name: "{{ tag_project }}-{{ tag_subproject }}"
      #name_suffix: "{{ name_end | default('new') }}"
      #name_env: "{{ project_name }}-{{ name_suffix }}"
      name_env: "{{ tag_subproject }}"
      prod_env: "{{ production | default(False) | bool }}"
  roles:
    - create_worker_instance
- include: provision_worker.yml
