---
- debug: msg="{{ ec2_id }}"
- pause: prompt="ctrl-C TO NOT START INSTANCES"
- name: start instance
  local_action:
    module: ec2
    state: running
    region: "{{ region }}"
    instance_ids: "{{ ec2_id }}"
