# terminate workers for this environment
---
- hosts: tag_Name_ingest_stage_worker
  gather_facts: yes
  tasks:
    - debug: msg="{{ ec2_id }}"
    - pause: prompt="ctrl-C TO NOT TERMINATE INSTANCES"
    - name: terminate workers
      local_action:
        module: ec2
        state: absent
        region: us-west-2
        wait: true
        wait_timeout: 500
        instance_ids: "{{ ec2_id }}"
