# terminate workers for this environment
---
- debug: msg="{{ ec2_id }}"
- pause: prompt="ctrl-C TO NOT TERMINATE INSTANCES"
- name: terminate workers
  local_action:
    module: ec2
    state: absent
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    wait: true
    wait_timeout: 500
