---
image_hvm: ami-dfc39aef
image_nat: ami-290f4119
instance_type: t2.micro
key_name: ingest
key_name_private: ingest
region: us-west-2 
vpc_id: vpc-51802634
subnet_id_public: subnet-ee63cf99
subnet_id_private: subnet-1bbe676c
sec_grp_NAT_id: sg-03185166
sec_grp_ingest_private:
  group_id: sg-95b298f0
sec_grp_front:
  group_id: sg-97b298f2
eip_ingest_front: 52.11.194.40
volume_size_couchdb: 164
volume_size_solr: 64
################################################################################
# access cidr lists for front end machine
################################################################################
cidr_cdlib: 128.48.204.0/24  #CDLIB subnet
cidr_registry: 128.48.120.185/32 #registry.cdlib.org
cidr_sb_cdlib: 192.35.209.136/32 #sb.cdlib.org
cidr_hedlok_deskbox: 128.48.204.194/32 #mark's linux desktop
cidr_list_dpla:
  - 54.84.55.179/32 #dev
  - 54.210.225.38/32 #dev
  - 54.165.98.52/32 #dev
  - 54.88.10.164/32 #stage
  - 54.86.130.204/32 #prod
cidr_ucsd_gabriela: 137.110.8.0/24
cidr_list_ucop_vpn: 
  - 128.48.254.0/24
  - 128.48.255.0/24
