---
- name: get ip of couchdb
  shell: cat /ip-couchdb
  register: ip_couchdb
- name: get ip of solr
  shell: cat /ip-solr
  register: ip_solr
- name: install httpd
  yum: pkg=httpd state=present
- name: install mod_ssl
  yum: pkg=mod_ssl state=present
- name: add ssl rewrite/forwarding conf
  template: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf
- name: start apache
  service: name=httpd enabled=yes state=started
#    - name: Display all variables/facts known for a host
#      debug: var=hostvars
- name: get redis docker image
  shell: docker pull redis
- name: get rq-dashboard docker image
  shell: docker pull mredar/rq-dashboard
#    - name: run couchdb docker
#      docker: image=tutum/couchdb command=/run.sh ports=5984
- debug: var=REDIS_PSWD
#TODO: setup stunnel and run redis on remote ???
- name: run redis docker
  docker:
    state: running
    image: redis
    name: redis
    ports: "6379:6379"
    command: "/entrypoint.sh redis-server --requirepass {{ REDIS_PSWD }}"
- name: run rq-dashboard docker
  docker: 
    state: running
    image: mredar/rq-dashboard
    name: rq-dashboard
    ports: "9181:9181"
    command: /run.sh ports=9181
    env: "REDIS_HOST={{ ansible_default_ipv4.address }},REDIS_PSWD={{ REDIS_PSWD }}"
