---
###- name: get ip of couchdb #this was for vagrant
###  shell: cat /ip-couchdb
###  register: ip_couchdb
###- name: get ip of solr
###  shell: cat /ip-solr
###  register: ip_solr
- name: copy access key for private machines
  sudo: no
  copy:
    src: ~/.ssh/ingest-west-2.pem
    dest: ~/.ssh/ingest-west-2.pem
    force: no
    mode: 0600
- name: make ingest key default
  sudo: no
  lineinfile:
    dest: ~/.ssh/config
    line: IdentityFile ~/.ssh/ingest-west-2.pem
    state: present
    mode: 0600
    backup: yes
    create: yes
- name: install mod_ssl
  yum: pkg=mod_ssl state=present
- name: install httpd
  yum: pkg=httpd state=present
- name: get httpd version
  shell: httpd -v | head -1 | sed -n 's/.*Apache\/\([0-9].[0-9]\).*/\1/p'
  register: httpd_version
- debug: msg="HTTPD VERSION -- {{ httpd_version.stdout }}"
- name: add ssl rewrite/forwarding conf
  template: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf
- name: remove port 80
  lineinfile: dest=/etc/httpd/conf/httpd.conf state=absent line="Listen 80"
- name: start apache
  service: name=httpd enabled=yes state=started
- name: put authorized_users file in place
  copy:
    src: authorized_users.pw
    dest: /etc/httpd/conf.d/authorized_users.pw
  notify:
    - restart apache
###TODO: setup stunnel and run redis on remote ???
- name: install stunnel
  yum: pkg=stunnel state=present
- name: run rq-dashboard docker
  docker: 
    #docker_api_version: docker_server_api_version.stdout
    state: running
    image: mredar/rq-dashboard
    name: rq-dashboard
    ports: "9181:9181"
    command: /run.sh ports=9181
    env: "REDIS_HOST={{ redis_endpoint_elasticcache }}" #,REDIS_PSWD={{ REDIS_PSWD }}"
